/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.Scanner;
/**
 *
 * @author user
 */
public class asis extends javax.swing.JFrame {
    private double angka;

    /**
     * Creates new form asis
     */
    public asis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soal = new javax.swing.JTextField();
        Soal1 = new javax.swing.JRadioButton();
        Soal2 = new javax.swing.JRadioButton();
        Soal3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        texta = new javax.swing.JTextField();
        textn = new javax.swing.JTextField();
        textx = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hasiltext = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        soal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soalActionPerformed(evt);
            }
        });

        Soal1.setText("SOAL 1");
        Soal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Soal1ActionPerformed(evt);
            }
        });

        Soal2.setText("SOAL 2");
        Soal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Soal2ActionPerformed(evt);
            }
        });

        Soal3.setText("SOAL 3");
        Soal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Soal3ActionPerformed(evt);
            }
        });

        jLabel1.setText("MASUKKAN NILAI");

        jLabel2.setText("a");

        jLabel3.setText("n");

        jLabel4.setText("x");

        hitung.setText("HITUNG");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        texta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textaActionPerformed(evt);
            }
        });

        textn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnActionPerformed(evt);
            }
        });

        textx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textxActionPerformed(evt);
            }
        });

        jLabel5.setText("HASIL =");

        hasiltext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasiltextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(hitung)
                .addGap(29, 29, 29)
                .addComponent(reset))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textx, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textn, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                        .addComponent(texta)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Soal2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Soal1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Soal3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(27, 27, 27)
                                .addComponent(soal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(hasiltext, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(soal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Soal1)
                                        .addGap(18, 18, 18)
                                        .addComponent(Soal2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(texta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(textn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Soal3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(textx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(hasiltext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(158, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reset)
                            .addComponent(hitung))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soalActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void Soal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Soal1ActionPerformed
soal.setText("f(x) = sin (2x)");        // TODO add your handling code here:
    }//GEN-LAST:event_Soal1ActionPerformed

    private void Soal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Soal2ActionPerformed
soal.setText("f(x) = x/(1-x)");       // TODO add your handling code here:
    }//GEN-LAST:event_Soal2ActionPerformed

    private void Soal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Soal3ActionPerformed
soal.setText("f(x) = xe^2x");        // TODO add your handling code here:
    }//GEN-LAST:event_Soal3ActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
// TODO add your handling code here:
        //hitung
        double n=Double.parseDouble(textn.getText());
        double a=Double.parseDouble(texta.getText());
        double x=Double.parseDouble(textx.getText());
        double hasil=0;
        double hasil1=0;
        int apa=1;
        double faktorial=1;
        for(int i=1;i<=n;i++)
        {
            faktorial=faktorial*i;
            apa++;
        }
        if("f(x) = sin (2x)".equals(soal.getText()))
        {
            for(int i=0;i<=n;i++)
            {
              hasil=hasil+(Math.pow(2,i) * Math.pow(x,i) * Math.pow(-1,i))/faktorial;
            }
        } 
        if("f(x) = x/(1-x)".equals(soal.getText()))
        {
            for(int i=0;i<=n;i++)
            {
                hasil1 = n*Math.pow(x,i+1);
                hasil= hasil+hasil1;
            }
        }
        hasiltext.setText(String.valueOf(hasil));
    }//GEN-LAST:event_hitungActionPerformed

    private void textnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnActionPerformed
        // TODO add your handling code here:
        double n;
        Scanner input = new Scanner(System.in);
        n = input.nextDouble();
    }//GEN-LAST:event_textnActionPerformed

    private void hasiltextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasiltextActionPerformed
        // TODO add your handling code here:
        //hasil
        
        
    }//GEN-LAST:event_hasiltextActionPerformed

    private void textaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textaActionPerformed
        // TODO add your handling code here:
        double a;
        Scanner input = new Scanner(System.in);
        a = input.nextDouble();
       // jLabel1.setText(a);

    }//GEN-LAST:event_textaActionPerformed

    private void textxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textxActionPerformed
        // TODO add your handling code here:
        double x;
        Scanner input = new Scanner(System.in);
        x = input.nextDouble();
    }//GEN-LAST:event_textxActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(asis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(asis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(asis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(asis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new asis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Soal1;
    private javax.swing.JRadioButton Soal2;
    private javax.swing.JRadioButton Soal3;
    private javax.swing.JTextField hasiltext;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton reset;
    private javax.swing.JTextField soal;
    private javax.swing.JTextField texta;
    private javax.swing.JTextField textn;
    private javax.swing.JTextField textx;
    // End of variables declaration//GEN-END:variables
}
